[package]
name = "light-node-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.1"
log = "0.4.17"
futures = "0.3.24"
async-std = "1.12.0"
smoldot = { path = "../../" }
smoldot-light = { path = "../light-base" }